### ISSUE TITLE
clean-css 4.x dependencie

### ISSUE THREAD

**Issue by kevin-loumont** [DazzlingFugu/ember-feature-controls#34]
We will need to delete the resolution deps of `clean-css` when ember-cli will upgrade his deps to ember-cli-preprocess-registry v4.x.x because it doens't use it anymore

`
//package.json
"resolutions": {
    "clean-css": "^4.1.11"
  }` 

it could also bring new issue with node.js 12
see: https://github.com/ember-cli/ember-cli-preprocess-registry/issues/71

**Comment by MrChocolatine** [comment]
The resolution to `clean-css@4.1.11` was removed in the pull request #126 (commit a6d6a25f03882d6d6c22e3186122144052f18988).

I am closing this issue.
